### ISSUE TITLE
USB network adapters not working

### ISSUE THREAD

**Issue by loswochos** [rg35xx-cfw/rg35xx-cfw.github.io#43] opened 2023-04-28 19:28 UTC
First, thanks for you hard work!

I've tried the following wifi/network adapters:
 
- Edimax EW-7811UN (RTL8188) with several USB-C to USB-A adapters 
- Belkin USB-C gigabit ethernet adapter

None of them are working. SSIDs are not detected (Edimax) when wifi is enabled. Also the ip configuration isn't available. 

It seems that usb in general is not working.

**Comment by loswochos** [comment] 2023-04-28 19:52
Sorry didn't see issue #31.

**Comment by acmeplus** [comment] 2023-04-28 23:21
> Sorry didn't see issue #31.

No worries, I'm going to close this ticket and continue the discussion on the other issue.

Duplicate of #31

**Closed by acmeplus** 2023-04-28 23:21 UTC
