### ISSUE TITLE
DS on v0.6

### ISSUE THREAD

**Issue by kirbydoggs** [rg35xx-cfw/rg35xx-cfw.github.io#40] opened 2023-04-27 22:43 UTC
I truly cannot get this to work. The drastic port is on the sd card and the script was placed in the right place. When I try to boot the game it says missing bios, then when I go to see what bios are missing, it says all of them even though I have them all on my SD card. What am I doing wrong? Can someone list some steps? Possibly bios? Thank you!

**Comment by acmeplus** [comment] 2023-04-28 01:18
See this comment, that should fix your issue:

https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/issues/25#issuecomment-1526845570

Closing as duplicate of #25

**Closed by acmeplus** 2023-04-28 01:18 UTC
